name: Test API
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [14.x, 16.x, 18.x]
  steps:
    - uses: actions/checkout@v2
    - name: Use node version ${{ matrix.node-version }}
      uses: actions/setup-node@v2
        with:
          node-version: matrix.node-version
    - run: npm test
